### ISSUE TITLE
Submodules offline

### ISSUE THREAD

**Issue by Cebion** [tycho/arc#1]
Hey @tycho ,

I wanted to compile this project but it seems all submodules are offline.
Do you have a copy or full source archive of arc?

Thanks in advance

**Comment by tycho** [comment]
This project isn't functionally complete in any way, so you would be happier finding some other one. But the .gitmodules file is out of date and should point to the https:// repos instead of git://... I could fix it at some point.

**Comment by Cebion** [comment]
> This project isn't functionally complete in any way, so you would be happier finding some other one. But the .gitmodules file is out of date and should point to the https:// repos instead of git://... I could fix it at some point.

Thank you, just looking for old projects to port to some linux handhelds. This would have been a nice addition.
I'll look into it.
